import AppLayout from "@/layouts/AppLayout";
import ThemeContextProvider from "@/theme";

import { notFound } from "next/navigation";

export const metadata = {
  title: "Md. Jueal Portfolio",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    locale?: string;
  };
}) {
  return (
    <html>
      <ThemeContextProvider>
        <body suppressHydrationWarning={true}>
          <AppLayout> {children}</AppLayout>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
